version: '3'
services:
  caddy:
    build: caddy
    environment:
      - DEPLOY_ENV=${DEPLOY_ENV}
      - HOST_DEV=${HOST_DEV}
      - HOST_PROD=${HOST_PROD}
      - ONION_HOST_PROD=${ONION_HOST_PROD}
      - ONION_HOST_DEV=${ONION_HOST_DEV}
    ports:
      # dev
      - "127.0.0.1:8080:8080"
      # prod
      - "80:80"
      - "443:443"
    volumes:
      - caddy_srv:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "100"
    networks:
      - cryptodog

  updog:
    build:
      context: updog
      args:
        DEPLOY_ENV: ${DEPLOY_ENV}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "100"
    networks:
      - cryptodog

  ejabberd:
    build:
      context: debian-ejabberd
      args:
        EJABBERD_HOSTNAME: ${EJABBERD_HOSTNAME}
    tmpfs:
      - /run/ejabberd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "100"
    networks:
      - cryptodog

  onion-service:
    build:
      context: onion-service
      args:
        DEPLOY_ENV: ${DEPLOY_ENV}
    volumes:
      - tor_data:/var/lib/tor
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "100"
    networks:
      - cryptodog

  updater:
    build: updater
    depends_on:
      # need caddy to start first; otherwise, setting perms on /srv is unreliable
      - caddy
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    volumes:
      - caddy_srv:/srv
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "100"
    networks:
      - cryptodog

volumes:
  caddy_srv:
  caddy_data:
    external: true
  caddy_config:
  tor_data:
    external: true

networks:
  cryptodog:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.27.0/16
          gateway: 192.168.27.1
